### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arturguitelar** [arturguitelar/godot-jogos-curso-udemy#1]
### Felpudo Fly
Refatorar código:
- [ ] Colocar os nomes das variáveis e demais elementos em inglês.
- [ ] Comentar o código.

### Timber Felpudo
Colocar som:
- [ ] Na marretada do bichinho.
- [ ] Quando o bichinho morre.
- [ ] Background.
